Библиотеки

In [2]:
import numpy as np

Константы

In [3]:
L = 10 #размер сетки
n = L * L
T = 32 #время

Создание кластера и первой заполненной точки

In [4]:
cluster = np.zeros((L, L))
x = np.random.randint(L)
y = np.random.randint(L)
cluster[x, y] = 1
print(cluster)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
def get_neighbors(x, y):
    for x_ in range(max(0, x - 1), min(L, x + 2)):
        for y_ in range(max(0, y - 1), min(L, y + 2)):
            if (x, y) == (x_, y_):
                continue
            cluster[x_, y_] = 2
            print(x_, y_)

neighbors = get_neighbors(x, y)
print(neighbors)
print(cluster)

6 7
6 8
6 9
7 7
7 9
8 7
8 8
8 9
None
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 2. 2. 2.]
 [0. 0. 0. 0. 0. 0. 0. 2. 1. 2.]
 [0. 0. 0. 0. 0. 0. 0. 2. 2. 2.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
